## Source Repos
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Non-technical Tools
cask "firefox"
#cask "google-chrome"
cask "grammarly"
cask "whatsapp"
#cask "transmission"
cask "spotify"
cask "rectangle"
cask "maccy"

# Technical Tools
cask "visual-studio-code"
#cask "powershell"
#cask "iterm2"
cask "postman"
cask "drawio"
brew "kubernetes-cli"
brew "nmap"
brew "watch"
brew "node"
#brew "azure-cli"
brew "awscli"
brew "python"
brew "nomad"
brew "consul"
brew "terraform"
brew "tfenv"
brew "terraform-docs"


cask "google-cloud-sdk"
brew "kubectl"
brew "helm"
brew "kubectx"
brew "kube-ps1"
# brew "python"
# brew "zsh"